Mini-Team-6/Mini-Team-6-Frontend

package-lock.json
package.json

[#1] chore : 라이브러리 설치

---

package-lock.json
package.json
public/mock/roomsData.json
src/App.tsx
src/components/Detail/DatePickModal.tsx
src/components/Detail/DetailDateAndCount.tsx
src/components/Detail/DetailSectionBottom.tsx
src/components/Detail/DetailSectionBottomBox.tsx
src/components/Header/Header.tsx
src/components/Room/RoomSectionBottom.tsx
src/components/Room/RoomSectionTop.tsx
src/hook/useDate.ts
src/pages/detailPage/DetailPage.tsx
src/pages/roomDetailPage/RoomDetailPage.tsx
src/store/memberCount.ts

[#21] feat : 상세 페이지 기능 구현 완료

---

package-lock.json
src/App.tsx
src/components/Context/UserContext.tsx
src/components/Header/Sidebar.tsx
src/pages/loginPage/LoginPage.tsx

회원가입할때만 Name정보를 받고 로그인정보를 받을때는 Name정보를 서버로부터 받아오고있지 않았더라고요... 
그래서 이메일 + 님 으로 로그인되게 하였고 그다음 로컬스토리지에 넣는걸로 바꾸었습니다.
zustand적용전에 이제까지 한 코드들 pr날립니다.
close #30

Fix: 로그인기능 스토리지에 저장 및 zustand 적용전 커밋

---

src/pages/searchPage/LocationSelect.tsx
src/pages/searchPage/SearchInput.tsx
src/pages/searchPage/SearchPage.tsx
src/pages/searchPage/SearchReslutList.tsx

- 백엔드에서 검색 데이터 없을시 에러를 반환하지 않는 처리를 한 뒤 확인 가능
close #24

[#24] refactor : 검색 페이지 state -> queryString 으로 데이터 관리 방법 변경

---

src/components/Main/CityList.tsx

design: 로딩 스피너 추가

---

src/components/Header/Header.tsx
src/components/Header/Sidebar.tsx

[#41] feat : 사이드바 메뉴버튼 추가

---

src/pages/searchPage/SearchPage.tsx
src/pages/searchPage/SearchReslutList.tsx
src/pages/searchPage/SkeletonSearchResultList.tsx

[#43] design : 검색페이지 로딩시 스켈레톤 디자인 추가

---

src/components/Main/CityItem.tsx

fix: keyword 수정

---

.github/workflows/playwright.yml
.gitignore
package-lock.json
package.json
playwright.config.ts
tests/example.spec.ts

[#55] chore : playwright 설치 및 github action 확인

---

src/api/search.ts
src/assets/icons/noResult.svg
src/pages/searchPage/SearchReslutList.tsx
src/pages/searchPage/SkeletonSearchResultList.tsx

[#54] feat : 검색 결과 없을 시 화면 추가

---

src/components/Store/UserStore.tsx
src/pages/myPage/MyPage.tsx

깜빡하고 이슈도 안만들고 브랜치도 안바꾸었네요 ㅠㅠ
마이페이지에 기능구현되었는데 백엔드 정보를 이메일과 닉네임정도 받아올수있어서 일단 그부분 반영되게 하였고
로그아웃기능도 구현해두었습니다.

Refact: 마이페이지 기능수정

---

tests/loginPage.spec.ts

[#64] feat : 회원가입 중복 체크 테스트 추가

---

playwright.config.ts
tests/searchPage.spec.ts

[#64] feat : 테스트 설정 변경 및 검섹페이지 테스트 수정

---

src/components/Main/CategoryTab.tsx
tests/mainPage.spec.ts

feat: 메인 페이지 테스트 코드 추가

---

src/pages/searchPage/SearchReslutList.tsx

[#75] refactor : 검색페이지 무한스크롤 개선

---

src/pages/myPage/MyPage.tsx

마이페이지 수정기능을 추가했습니다.
수정버튼을 누르면 수정되고 로컬스토리지에 반영되고 닉네임변경이 가능해졌습니다.
close #61

마이페이지 수정기능 추가

---

src/api/detail.ts
src/components/Detail/DatePickModal.tsx
src/components/Detail/DetailDateAndCount.tsx
src/components/Detail/DetailNoPage.tsx
src/components/Detail/DetailSectionBottom.tsx
src/components/Detail/DetailSectionBottomBox.tsx
src/pages/detailPage/DetailPage.tsx

Refactor: API 쿼리사용 및 토큰 검증

---

src/components/Reservation/HistoryRoom.tsx
src/pages/reservationPage/ReservationHistoryPage.tsx

Fix: 미사용 변수 제거

---

src/components/Reservation/ActualUserInfoSection.tsx
src/components/Reservation/HistoryRoom.tsx
src/components/Reservation/ReservationHistoryItem.tsx
src/components/Reservation/ReservationInfoSection.tsx
src/components/Reservation/ReservationPersonInfoSection.tsx
src/pages/reservationPage/ReservationHistoryPage.tsx

[#44] Feat: 예약 내역 페이지 api 연동 완료 및 상세보기 경로 추가

---

src/pages/reservationPage/ReservationHistoryPage.tsx

Fix: 불필요한 console.log 제거

---

tests/cartPage.spec.ts
tests/detailPage.spec.ts

feat : 상세 페이지, 장바구니 페이지 E2E 테스트 코드 추가

---

src/components/Reservation/ReservationHistoryItem.tsx
tests/reservationPage.spec.ts

Feat: 예약페이지 테스트코드

---

README.md

docs : readme.md 업데이트

---

src/pages/searchPage/LocationSelect.tsx

[#97] refactor : 상수 데이터 컴포넌트 외부 선언

---

src/components/Header/Header.tsx

[#99] refactor : Header.tsx 수정

---

index.html
src/pages/myPage/MyPage.tsx

Refact: 마이페이지 리팩토링

---

src/api/reservation.ts

Refactor: axios instance 생성시 baseURL과 header 추가

---

src/api/reservation.ts
src/components/Reservation/ReservationInfoSection.tsx
src/pages/reservationPage/ReservationPage.tsx
src/types/reservationTypes.ts

Refactor: Type-only import export 적용

---

src/api/cart.ts
src/api/detail.ts
src/components/Cart/CartResevation.tsx
src/components/Cart/CartSectionBox.tsx
src/components/Detail/DatePickModal.tsx
src/components/Detail/DetailDateAndCount.tsx
src/components/Detail/DetailSectionBottom.tsx
src/store/memberCount.ts

* 중복된(불필요한) 변수 => 메소드 체이닝 등 정리
* 일부 변수명 변경
* 구조분해할당 최대 사용
close #100

refactor: 상세, 장바구니 페이지 리팩토링

---

package-lock.json
package.json
src/components/Main/CategoryTab.tsx
src/components/Main/CityList.tsx
src/components/Main/Constant/areaCategory.ts
src/components/Main/ErrorPage.tsx
src/components/Main/MainCarousel.tsx
src/components/Main/SkeletonPage.tsx
src/pages/mainPage/MainPage.tsx

#111 refactor: suspense, error boundary 적용 메인 페이지 리팩토링
